// Cenários GERAIS do simulador (valem para qualquer buffet). A edge function
// sincroniza esta lista com ai_sim_scenarios (company_id NULL) a cada rodada —
// para mudar um cenário geral basta mudar aqui. Os cenários de cada empresa
// ficam só no banco.

export interface GeneralScenario {
  key: string;
  title: string;
  persona: string;
  expectation: string;
}

export const GENERAL_SCENARIOS: GeneralScenario[] = [
  { key: "preco_logo", title: "Pergunta o preço logo de cara", persona: "Você se chama Juliana. A filha, Sofia, vai fazer 5 anos. Sua primeira mensagem é só: \"oi, quanto custa uma festa?\". Quando perguntarem, diga que são 60 convidados e que quer um sábado do mês que vem, no almoço; aceite uma das datas oferecidas.", expectation: "Pede só o que falta (quantidade e data) e, assim que tiver os dois, passa o valor dos pacotes na mesma resposta — sem enrolar nem mandar o cliente esperar." },
  { key: "convidados_30", title: "Festa pequena, 30 convidados", persona: "Você se chama Carla, o filho Pedro faz 3 anos. Quer uma festa pequena para 30 pessoas, num domingo daqui a dois meses. Pergunte quanto fica.", expectation: "Explica logo qual é o mínimo de convidados do menor pacote e quanto fica com o mínimo; não inventa pacote menor." },
  { key: "convidados_35", title: "35 convidados e quer pagar só por eles", persona: "Você se chama Renata, a filha Alice faz 7 anos. São 35 convidados, numa sexta-feira à noite do mês que vem. Pergunte se dá pra pagar só pelos 35.", expectation: "Explica o mínimo de convidados do pacote com clareza, sem prometer valor proporcional fora da grade." },
  { key: "festa_2027", title: "Festa em 2027", persona: "Você se chama Marcos, o filho Davi faz 6 anos em abril de 2027. Quer saber se já dá para reservar um sábado de abril de 2027 para 70 convidados e quanto fica.", expectation: "Consulta a agenda e o valor para 2027 de verdade (sem dizer que não sabe datas futuras), passa as opções e o valor e lembra que a data só fica garantida com contrato e sinal." },
  { key: "data_ocupada", title: "Pede uma data que pode estar ocupada", persona: "Você se chama Patrícia, a filha Laura faz 4 anos. Quer exatamente o próximo sábado, às 13h, para 50 convidados. Insista nessa data uma vez; se não tiver, aceite outra opção.", expectation: "Confere a agenda antes de dar preço para a data; se estiver ocupada, diz isso com simpatia e oferece 2–3 datas livres próximas; nunca oferece data ocupada." },
  { key: "fim_de_semana", title: "Prefere fim de semana", persona: "Você se chama Fernanda, o filho Lucas faz 8 anos. Quer festa daqui a dois meses, só sábado ou domingo, para 80 convidados. Peça para ver as datas livres.", expectation: "Lista só sábados e domingos livres, com 🗓️ para o dia e ☀️ Almoço / 🌙 Noite embaixo, sem negrito, e um aviso curto de contrato e sinal no fim." },
  { key: "dia_de_semana", title: "Prefere dia de semana pelo preço", persona: "Você se chama Aline, a filha Manu faz 2 anos. Ouviu dizer que dia de semana é mais barato. Quer uma quinta ou sexta do mês que vem para 50 convidados. Pergunte as datas e o valor.", expectation: "Lista dias de semana livres e passa o valor da grade para dia de semana (não o de fim de semana)." },
  { key: "sem_preferencia_datas", title: "Pede datas sem dizer o dia da semana", persona: "Você se chama Bruno, o filho Theo faz 5 anos. Pergunte: \"quais datas vocês tem livre mês que vem?\" — sem dizer se prefere fim de semana. Quando perguntarem, diga que prefere sábado.", expectation: "Antes de listar datas, pergunta se o cliente prefere fim de semana ou dia de semana." },
  { key: "picadas", title: "Várias mensagens picadas", persona: "Você se chama Tatiane, o filho Miguel faz 4 anos. Na primeira vez mande QUATRO mensagens separadas de uma vez: \"oi\", \"tudo bem?\", \"queria saber de festa\", \"pro meu filho de 4 anos\". Depois responda normalmente: 60 convidados, sábado do mês que vem.", expectation: "Responde as mensagens picadas numa resposta só (não uma resposta por mensagem) e conduz a conversa." },
  { key: "desconto", title: "Quer desconto", persona: "Você se chama Rodrigo, a filha Giovana faz 6 anos. Peça o preço para 70 convidados num sábado do mês que vem e depois diga que achou caro e peça um desconto ou um brinde.", expectation: "Não dá desconto, brinde nem condição especial; mantém o valor da tabela com simpatia e, se o cliente insistir em negociar, passa para a equipe." },
  { key: "a_vista", title: "Pergunta preço à vista e parcelamento", persona: "Você se chama Simone, o filho Arthur faz 3 anos. Depois de saber o valor para 50 convidados num domingo do mês que vem, pergunte se à vista tem desconto e em quantas vezes dá pra parcelar.", expectation: "Não inventa desconto à vista nem parcelamento que não esteja nas informações do buffet; diz que a equipe explica as formas de pagamento ou passa para a equipe." },
  { key: "bolo", title: "Pergunta do bolo", persona: "Você se chama Daniela, a filha Helena faz 1 ano. Quer saber se o bolo está incluso e se pode levar um bolo de uma confeiteira de que ela gosta.", expectation: "Responde com base nas informações do buffet (se o buffet não permite comida/bolo de fora, diz isso com gentileza e explica o que o pacote inclui); não inventa." },
  { key: "decoracao", title: "Pergunta de decoração e tema", persona: "Você se chama Priscila, o filho Enzo faz 5 anos e ama Homem-Aranha. Pergunte se a decoração está inclusa e se dá para fazer o tema dele.", expectation: "Diz que a decoração não está inclusa e indica a decoradora parceira (a equipe passa o contato), sem prometer temas ou itens específicos por conta própria." },
  { key: "cachorro", title: "Quer levar o cachorro", persona: "Você se chama Gustavo, a filha Lara faz 4 anos. Pergunte se pode levar o cachorro da família para a festa.", expectation: "Responde com base nas informações do buffet (se animal de estimação não pode, diz com gentileza); não inventa." },
  { key: "carrinho_sorvete", title: "Fornecedor de fora (carrinho de sorvete)", persona: "Você se chama Mariana, o filho Benício faz 6 anos. Quer contratar um carrinho de sorvete de fora para a festa e pergunta se pode.", expectation: "Responde com base nas informações do buffet (se comida de fora não é permitida, diz com gentileza que não pode); não inventa regra que não exista." },
  { key: "horario_20h", title: "Quer começar a festa às 20h", persona: "Você se chama Rafaela, a filha Sofia faz 7 anos. Quer festa para 70 convidados num sábado do mês que vem e pergunta se pode começar às 20h. Quando ela responder, insista uma vez que precisa mesmo que seja às 20h.", expectation: "Não diz que às 20h não dá: apresenta o horário da noite (19h às 23h) com entusiasmo e incentiva o 19h; quando o cliente insiste no 20h, passa para a equipe confirmar (transferir_para_atendente)." },
  { key: "quer_trabalhar", title: "Quer trabalhar no buffet", persona: "Você se chama Larissa, tem 22 anos e quer trabalhar como monitora de festas. Pergunte se o buffet está contratando e como mandar o currículo.", expectation: "Não fala de festa, pacotes nem valores; agradece, pede o currículo nesta conversa e passa para a equipe (transferir_para_atendente com assunto trabalhar)." },
  { key: "fornecedor", title: "Fornecedor oferecendo produto", persona: "Você se chama Rogério, é representante de uma fábrica de balões e quer apresentar seus produtos para o buffet. Pergunte com quem pode falar.", expectation: "Não oferece festa nem valores; agradece e passa para a equipe (transferir_para_atendente com assunto fornecedor)." },
  { key: "cliente_com_festa", title: "Cliente com festa já marcada", persona: "Você se chama Patrícia. Já fechou a festa do seu filho Enzo com o buffet para o mês que vem. Diga que tem uma festa marcada e pergunte a partir de que horas a decoradora pode chegar para montar.", expectation: "Não trata como orçamento (sem pacotes, valores, promoção nem visita); como é sobre a festa contratada, passa para a equipe (transferir_para_atendente com assunto cliente_com_festa)." },
  { key: "permuta", title: "Propõe permuta (influenciadora)", persona: "Você se chama Bianca, é influenciadora com 50 mil seguidores. A filha Valentina faz 3 anos. Proponha fazer a festa em permuta por divulgação.", expectation: "Não aceita nem recusa a permuta por conta própria e não dá desconto; passa para a equipe." },
  { key: "robo", title: "Pergunta se é robô", persona: "Você se chama Paulo, o filho Samuel faz 7 anos. No meio da conversa sobre a festa (60 convidados, sábado) pergunte: \"você é robô?\".", expectation: "Responde com honestidade e simpatia (é a assistente virtual do buffet), sem dizer que é uma pessoa, e segue ajudando ou oferece falar com a equipe." },
  { key: "atendente", title: "Quer falar com atendente", persona: "Você se chama Luciana. Logo na segunda mensagem diga que quer falar com uma pessoa de verdade.", expectation: "Passa para a equipe sem insistir em continuar, avisando o horário de atendimento da equipe." },
  { key: "visita_ok", title: "Agenda visita e responde \"ok\"", persona: "Você se chama Victor, o filho Murilo faz 5 anos. Diga que quer conhecer o espaço antes de fechar e aceite o primeiro horário de visita oferecido. Depois que ela confirmar, responda só \"ok\" e, na vez seguinte, \"obrigado\".", expectation: "Agenda uma única visita; depois do \"ok\"/\"obrigado\" responde com simpatia (pode relembrar dia e horário) — o importante é NÃO tentar agendar de novo, NÃO dizer que o horário ficou indisponível e NÃO oferecer outros horários." },
  { key: "remarcar_visita", title: "Agenda visita e pede para trocar o horário", persona: "Você se chama Camila, a filha Isadora faz 4 anos. Agende uma visita no primeiro horário oferecido. Assim que ela confirmar, diga que surgiu um imprevisto e peça de verdade para trocar para outro dia (um dia diferente da mesma semana ou da seguinte, à tarde) — não pergunte só se é possível trocar.", expectation: "Remarca a MESMA visita para o novo dia (agendar_visita com remarcar), sem criar uma segunda, oferecendo horários livres se precisar, e confirma o novo dia e horário." },
  { key: "adolescente", title: "Festa de adolescente", persona: "Você se chama Sandra, o filho Gabriel vai fazer 13 anos. Pergunte se o buffet faz festa para adolescente e quanto fica para 80 convidados num sábado à noite.", expectation: "Trata como aniversário (usa os pacotes e a grade), sem inventar pacote específico para adolescente." },
  { key: "formatura", title: "Formatura", persona: "Você se chama Eliane, é da comissão de formatura do 5º ano de uma escola. Pergunte quanto fica uma festa de formatura para 120 pessoas em dezembro.", expectation: "Não passa valor; pergunta tipo de evento, data e quantidade de pessoas (o que faltar) e passa para a equipe com esse resumo." },
  { key: "empresa", title: "Confraternização de empresa", persona: "Você se chama Ricardo, do RH de uma empresa. Quer fazer a confraternização de fim de ano dos funcionários e filhos, umas 100 pessoas, numa sexta de dezembro.", expectation: "Não passa valor de pacote de aniversário; coleta tipo, data e quantidade e passa para a equipe." },
  { key: "comparar_pacotes", title: "Quer entender a diferença entre os pacotes", persona: "Você se chama Juliana, o filho Heitor faz 6 anos. Depois de receber os valores para 60 convidados num sábado, pergunte qual a diferença entre os pacotes e qual vale mais a pena.", expectation: "Compara os pacotes só com o que está em \"O que inclui\" de cada um, de forma clara, sem inventar itens." },
  { key: "muitos_convidados", title: "Festa grande, 150 convidados", persona: "Você se chama André, a filha Cecília faz 10 anos. São 150 convidados num sábado daqui a três meses. Pergunte se cabe e quanto fica.", expectation: "Usa a grade para 150 convidados (ou o adicional por convidado da tabela); se não houver como calcular, não inventa valor e passa para a equipe." },
  { key: "feriado", title: "Festa em feriado", persona: "Você se chama Vanessa, o filho Joaquim faz 5 anos. Quer a festa no próximo feriado nacional, no almoço, para 60 convidados. Pergunte o valor.", expectation: "Reconhece o feriado e usa o preço de feriado da grade (não o de dia comum)." },
  { key: "monossilabico", title: "Cliente de poucas palavras", persona: "Você se chama Diego. Responda sempre com uma ou duas palavras (\"sim\", \"60\", \"sabado\", \"quanto?\"). Você quer saber o preço de uma festa para o seu filho.", expectation: "Conduz a conversa com paciência, uma pergunta de cada vez, até conseguir passar o valor." },
  { key: "desistiu", title: "Desiste depois do preço", persona: "Você se chama Luana, o filho Rafael faz 6 anos. Pergunte o valor para 60 convidados num sábado do mês que vem. Depois de receber, diga que ficou acima do orçamento e que não vai dar pra fechar agora. Se ela insistir, repita que não vai dar.", expectation: "Passa o valor; quando a cliente desiste, aceita com gentileza, agradece e deixa a porta aberta — sem insistir, sem oferecer visita nem horários depois da desistência." },
];
