
INSERT INTO public.company_landing_pages (company_id, is_published, hero, theme, gallery, video, testimonials, offer, benefits, footer, social_proof, how_it_works)
VALUES (
  '84f6a011-a1e1-4a2a-96f6-38da92a319ce',
  true,
  '{"title":"Buffet Mega Magic Premium","subtitle":"O lugar perfeito para a festa dos sonhos do seu filho! Diversão garantida em São Paulo.","cta_text":"Solicitar Orçamento","background_image":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611871035.jpeg","background_overlay":0.5}'::jsonb,
  '{"primary_color":"#7B2D8E","secondary_color":"#D4A017","accent_color":"#F5C518","background_color":"#FDFBF7","text_color":"#2D2D2D","heading_font":"Poppins","body_font":"Inter"}'::jsonb,
  '{"enabled":true,"title":"Conheça Nosso Espaço","subtitle":"Um ambiente mágico preparado para encantar crianças e adultos","images":[{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611871035.jpeg","alt":"Mega Magic 1"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611871872.jpeg","alt":"Mega Magic 2"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611872258.jpeg","alt":"Mega Magic 3"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611872562.jpeg","alt":"Mega Magic 4"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611872921.jpeg","alt":"Mega Magic 5"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611873242.jpeg","alt":"Mega Magic 6"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611873580.jpeg","alt":"Mega Magic 7"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611873945.jpeg","alt":"Mega Magic 8"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775611993083.jpeg","alt":"Mega Magic 9"},{"url":"https://rsezgnkfhodltrsewlhz.supabase.co/storage/v1/object/public/onboarding-uploads/84f6a011-a1e1-4a2a-96f6-38da92a319ce/photos/1775612016244.jpeg","alt":"Mega Magic 10"}]}'::jsonb,
  '{"enabled":false,"title":"Veja Como é Uma Festa no Mega Magic","url":""}'::jsonb,
  '{"enabled":true,"title":"O Que Dizem Nossos Clientes","items":[{"name":"Ana Paula","text":"Festa maravilhosa! Meu filho amou cada segundo. Equipe super atenciosa e espaço incrível!","rating":5},{"name":"Carla Souza","text":"Melhor buffet que já fizemos festa! Organização impecável e as crianças se divertiram muito.","rating":5},{"name":"Marcos Silva","text":"Superou nossas expectativas! Decoração linda e comida deliciosa. Super recomendo!","rating":5}]}'::jsonb,
  '{"enabled":true,"title":"Garanta a Festa Perfeita","subtitle":"Solicite um orçamento personalizado e descubra as condições especiais","cta_text":"Quero Meu Orçamento","urgency_text":"Datas limitadas para os próximos meses!"}'::jsonb,
  '{"enabled":true,"title":"Por Que Escolher o Mega Magic?","subtitle":"Tudo pensado para uma festa inesquecível","items":[{"icon":"🎉","title":"Diversão Garantida","description":"Brinquedos e atividades para todas as idades"},{"icon":"🍕","title":"Cardápio Completo","description":"Comida deliciosa para crianças e adultos"},{"icon":"✨","title":"Decoração Temática","description":"Ambientes decorados com os temas mais pedidos"},{"icon":"👨‍👩‍👧‍👦","title":"Equipe Dedicada","description":"Monitores e recreadores treinados para cuidar de tudo"}],"trust_badges":[]}'::jsonb,
  '{"enabled":true,"show_logo":true,"show_social":true,"show_address":true,"address":"São Paulo - SP","copyright_text":"© 2026 Buffet Mega Magic Premium. Todos os direitos reservados."}'::jsonb,
  '{"enabled":true,"items":[{"value":"500+","label":"Festas Realizadas"},{"value":"10k+","label":"Crianças Felizes"},{"value":"5⭐","label":"Avaliação Google"}],"text":""}'::jsonb,
  '{"enabled":true,"title":"Como Funciona","steps":[{"title":"Solicite um Orçamento","description":"Preencha o formulário com os dados da festa"},{"title":"Escolha o Pacote","description":"Nossa equipe vai apresentar as melhores opções"},{"title":"Celebre!","description":"É só chegar e aproveitar a festa com a família"}]}'::jsonb
);
